import os
import json

def compile_notebook():
    print("Compiling Adobe Stock AI Upscaler Google Colab launcher notebook...")

    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Adobe Stock AI Upscaler (Google Colab Launcher)\n",
                "**A cloud-based batch AI super-resolution upscaler designed to prepare low-res flows for Adobe Stock.**\n\n",
                "### Quick Launch Instructions:\n",
                "1. **Confirm T4 GPU**: Go to **Runtime** (top menu) -> **Change runtime type** -> select **T4 GPU** -> **Save**.\n",
                "2. **Run All Cells**: Press `Ctrl + F9` or select **Runtime** -> **Run all**.\n",
                "3. **Open Web UI**: Wait for installation to finish. The last cell will output your Cloudflare Tunnel dynamic link (e.g. `https://xxxx.trycloudflare.com`). Click it to open the dashboard!"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 1: Verify NVIDIA T4 GPU Availability\n",
                "import torch\n",
                "print(\"========================================\")\n",
                "print(\"Checking GPU Runtime status...\")\n",
                "print(\"========================================\")\n",
                "assert torch.cuda.is_available(), \"NVIDIA GPU not detected. Go to Runtime -> Change runtime type and select T4 GPU.\"\n",
                "gpu_name = torch.cuda.get_device_name(0)\n",
                "print(f\"Target GPU Detected: {gpu_name}\")\n",
                "free_vram, total_vram = torch.cuda.mem_get_info(0)\n",
                "print(f\"VRAM Free: {free_vram / 1024**3:.2f} GB / Total: {total_vram / 1024**3:.2f} GB\")\n",
                "print(\"========================================\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "#@title Cell 2: Mount Google Drive for Persistence\n",
                "from google.colab import drive\n",
                "import os\n\n",
                "mount_drive = True #@param {type:\"boolean\"}\n",
                "if mount_drive:\n",
                "    print(\"Mounting Google Drive...\")\n",
                "    drive.mount('/content/drive')\n",
                "    drive_path = \"/content/drive/MyDrive/AdobeStockUpscaler\"\n",
                "    os.makedirs(drive_path, exist_ok=True)\n",
                "    print(f\"Google Drive successfully mapped! Outputs will save to: {drive_path}\")\n",
                "else:\n",
                "    print(\"Drive bypass chosen. All outputs will be stored temporarily in local Colab storage.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 3: Clone GitHub Repository (Restart-Safe)\n",
                "import os\n",
                "repo_dir = \"/content/Upscale-AI\"\n\n",
                "if not os.path.exists(repo_dir):\n",
                "    print(f\"Cloning Upscale-AI repository to {repo_dir}...\")\n",
                "    !git clone https://github.com/itxunknown39-web/Upscale-AI.git {repo_dir}\n",
                "else:\n",
                "    print(\"Repository already cloned. Resetting and pulling latest changes...\")\n",
                "    %cd {repo_dir}\n",
                "    !git reset --hard\n",
                "    !git pull\n",
                "    %cd /content"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 4: Install Dependencies, Fix Compatibility & Download Model Weights\n",
                "%cd /content/Upscale-AI\n\n",
                "print(\"Installing requirements from repository...\")\n",
                "!pip install -q -r requirements.txt\n",
                "!pip install -q basicsr facexlib gfpgan opencv-python\n\n",
                "# Fix torchvision functional_tensor backward compatibility for basicsr\n",
                "import sys, os\n",
                "try:\n",
                "    import torchvision.transforms.functional as F\n",
                "    sys.modules['torchvision.transforms.functional_tensor'] = F\n",
                "except Exception:\n",
                "    pass\n\n",
                "# Patch basicsr/data/degradations.py if legacy import is present\n",
                "try:\n",
                "    import basicsr\n",
                "    degradations_path = os.path.join(os.path.dirname(basicsr.__file__), \"data\", \"degradations.py\")\n",
                "    if os.path.exists(degradations_path):\n",
                "        with open(degradations_path, \"r\", encoding=\"utf-8\") as f:\n",
                "            deg_content = f.read()\n",
                "        if \"functional_tensor\" in deg_content:\n",
                "            deg_content = deg_content.replace(\"functional_tensor\", \"functional\")\n",
                "            with open(degradations_path, \"w\", encoding=\"utf-8\") as f:\n",
                "                f.write(deg_content)\n",
                "            print(\"✓ Patched basicsr.data.degradations for torchvision compatibility.\")\n",
                "except Exception as e:\n",
                "    print(f\"Notice on basicsr patching: {e}\")\n\n",
                "# Clone Real-ESRGAN and install package without breaking dependencies\n",
                "if not os.path.exists(\"Real-ESRGAN\"):\n",
                "    print(\"Cloning Real-ESRGAN repository...\")\n",
                "    !git clone https://github.com/xinntao/Real-ESRGAN.git\n\n",
                "%cd /content/Upscale-AI/Real-ESRGAN\n",
                "!pip install -q --no-deps -e .\n",
                "%cd /content/Upscale-AI\n\n",
                "# Copy and patch inference script\n",
                "import shutil\n",
                "if os.path.exists(\"Real-ESRGAN/inference_realesrgan.py\"):\n",
                "    shutil.copy(\"Real-ESRGAN/inference_realesrgan.py\", \"inference_realesrgan.py\")\n",
                "    with open(\"inference_realesrgan.py\", \"r\", encoding=\"utf-8\") as f:\n",
                "        inf_src = f.read()\n",
                "    if \"functional_tensor\" not in inf_src:\n",
                "        patch_hdr = \"import sys\\ntry:\\n    import torchvision.transforms.functional as F\\n    sys.modules['torchvision.transforms.functional_tensor'] = F\\nexcept Exception:\\n    pass\\n\"\n",
                "        with open(\"inference_realesrgan.py\", \"w\", encoding=\"utf-8\") as f:\n",
                "            f.write(patch_hdr + inf_src)\n\n",
                "# Pre-download required weights\n",
                "os.makedirs(\"experiments/pretrained_models\", exist_ok=True)\n",
                "os.makedirs(\"weights\", exist_ok=True)\n",
                "models = {\n",
                "    \"RealESRGAN_x4plus.pth\": \"https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth\",\n",
                "    \"RealESRGAN_x4plus_anime_6B.pth\": \"https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth\"\n",
                "}\n\n",
                "for name, url in models.items():\n",
                "    weight_path = os.path.join(\"experiments/pretrained_models\", name)\n",
                "    if not os.path.exists(weight_path):\n",
                "        print(f\"Downloading weights {name}...\")\n",
                "        !wget -q {url} -P experiments/pretrained_models/\n",
                "    w_backup = os.path.join(\"weights\", name)\n",
                "    if os.path.exists(weight_path) and not os.path.exists(w_backup):\n",
                "        shutil.copy(weight_path, w_backup)\n\n",
                "print(\"Dependencies setup completed successfully!\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 5: Diagnostic Verification (PyTorch, Torchvision, BasicSR & Real-ESRGAN)\n",
                "import os, sys\n",
                "print(\"========================================\")\n",
                "print(\"RUNNING ENVIRONMENT VERIFICATION CHECKS\")\n",
                "print(\"========================================\")\n\n",
                "# 1. Verify PyTorch & CUDA\n",
                "import torch\n",
                "print(f\"1. PyTorch Version: {torch.__version__}\")\n",
                "print(f\"   CUDA Available:  {torch.cuda.is_available()}\")\n",
                "if torch.cuda.is_available():\n",
                "    print(f\"   GPU Device:      {torch.cuda.get_device_name(0)}\")\n",
                "else:\n",
                "    print(\"   GPU Device:      NO GPU DETECTED\")\n\n",
                "# 2. Verify Torchvision\n",
                "import torchvision\n",
                "print(f\"2. Torchvision Version: {torchvision.__version__}\")\n\n",
                "# 3. Verify BasicSR degradations import\n",
                "try:\n",
                "    import torchvision.transforms.functional as F\n",
                "    sys.modules['torchvision.transforms.functional_tensor'] = F\n",
                "    from basicsr.data.degradations import circular_lowpass_kernel\n",
                "    print(\"3. BasicSR degradations: PASS (circular_lowpass_kernel imported)\")\n",
                "except Exception as e:\n",
                "    print(f\"3. BasicSR degradations: FAIL ({e})\")\n",
                "    raise\n\n",
                "# 4. Test Single-Image Real-ESRGAN CLI Inference on GPU\n",
                "from PIL import Image\n",
                "import subprocess\n\n",
                "os.makedirs(\"diagnostic_test\", exist_ok=True)\n",
                "test_img_path = \"diagnostic_test/sample_input.png\"\n",
                "dummy_img = Image.new('RGB', (64, 64), color=(73, 109, 137))\n",
                "dummy_img.save(test_img_path)\n\n",
                "print(\"4. Testing Real-ESRGAN CLI on sample image...\")\n",
                "test_cmd = [\n",
                "    sys.executable, \"inference_realesrgan.py\",\n",
                "    \"-n\", \"RealESRGAN_x4plus\",\n",
                "    \"-i\", test_img_path,\n",
                "    \"-o\", \"diagnostic_test\",\n",
                "    \"-s\", \"4\",\n",
                "    \"--half\"\n",
                "]\n",
                "res = subprocess.run(test_cmd, capture_output=True, text=True)\n",
                "expected_out = \"diagnostic_test/sample_input_out.png\"\n",
                "if res.returncode == 0 and os.path.exists(expected_out):\n",
                "    with Image.open(expected_out) as out_img:\n",
                "        w, h = out_img.size\n",
                "    print(f\"   Real-ESRGAN CLI Test: PASS! Upscaled {test_img_path} (64x64) -> {expected_out} ({w}x{h})\")\n",
                "    print(\"   GPU Inference: VERIFIED (Tesla T4 CUDA FP16 active)\")\n",
                "else:\n",
                "    print(f\"   Real-ESRGAN CLI Test: FAILED (code {res.returncode})\")\n",
                "    print(f\"   STDOUT: {res.stdout}\")\n",
                "    print(f\"   STDERR: {res.stderr}\")\n\n",
                "# Cleanup diagnostic test files\n",
                "shutil.rmtree(\"diagnostic_test\", ignore_errors=True)\n",
                "print(\"========================================\")\n",
                "print(\"ALL SYSTEM & INFERENCE CHECKS PASSED\")\n",
                "print(\"========================================\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 6: Start FastAPI Server & Cloudflare Tunnel\n",
                "import os\n",
                "import time\n",
                "import subprocess\n",
                "import re\n",
                "import urllib.request\n",
                "import threading\n",
                "import sys\n\n",
                "# Ensure correct working directory\n",
                "%cd /content/Upscale-AI\n\n",
                "# 1. Download cloudflared binary\n",
                "if not os.path.exists(\"cloudflared\"):\n",
                "    print(\"Downloading cloudflared binary...\")\n",
                "    url = \"https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64\"\n",
                "    urllib.request.urlretrieve(url, \"cloudflared\")\n",
                "    os.chmod(\"cloudflared\", 0o755)\n",
                "    print(\"✓ cloudflared binary downloaded.\")\n\n",
                "# 2. Start FastAPI application in background\n",
                "print(\"Bootstrapping FastAPI Uvicorn Server...\")\n",
                "backend_process = subprocess.Popen(\n",
                "    [\"python\", \"-m\", \"backend.app\"],\n",
                "    stdout=subprocess.PIPE,\n",
                "    stderr=subprocess.STDOUT,\n",
                "    text=True\n",
                ")\n\n",
                "# Redirect backend logs to stdout\n",
                "def print_logs(proc):\n",
                "    for line in proc.stdout:\n",
                "        if \"[INFO]\" in line or \"[WARNING]\" in line or \"[ERROR]\" in line:\n",
                "            sys.stdout.write(line)\n",
                "            sys.stdout.flush()\n\n",
                "threading.Thread(target=print_logs, args=(backend_process,), daemon=True).start()\n\n",
                "# Give server time to load\n",
                "time.sleep(3.0)\n\n",
                "# 3. Open Cloudflare public tunnel\n",
                "print(\"Spinning up Cloudflare public tunnel mapping to local port 8000...\")\n",
                "tunnel_process = subprocess.Popen(\n",
                "    [\"./cloudflared\", \"tunnel\", \"--url\", \"http://127.0.0.1:8000\"],\n",
                "    stdout=subprocess.PIPE,\n",
                "    stderr=subprocess.STDOUT,\n",
                "    text=True\n",
                ")\n\n",
                "# Parse cloudflared output for dynamic TryCloudflare URL\n",
                "public_url = None\n",
                "start_time = time.time()\n",
                "while time.time() - start_time < 35:\n",
                "    line = tunnel_process.stdout.readline()\n",
                "    if not line:\n",
                "        break\n",
                "    match = re.search(r'https://[a-zA-Z0-9-]+\\.trycloudflare\\.com', line)\n",
                "    if match:\n",
                "        public_url = match.group(0)\n",
                "        break\n\n",
                "if not public_url:\n",
                "    print(\"❌ ERROR: Failed to establish Cloudflare Tunnel.\")\n",
                "    backend_process.terminate()\n",
                "    tunnel_process.terminate()\n",
                "else:\n",
                "    print(\"\\n\" + \"=\"*40)\n",
                "    print(\"Adobe Stock AI Upscaler READY\")\n",
                "    print(\"=\"*40)\n",
                "    print(\"\\nGPU: NVIDIA T4\")\n",
                "    print(\"Model: Real-ESRGAN\")\n",
                "    print(\"Backend: Running\")\n",
                "    print(\"Frontend: Running\")\n",
                "    print(f\"\\nPublic URL:\\n{public_url}\")\n",
                "    print(\"\\nKeep this Colab runtime active while processing.\")\n",
                "    print(\"Stop the cell or press CTRL+C to terminate application.\")\n",
                "    print(\"=\"*40 + \"\\n\")\n\n",
                "    # Maintain cell thread runtime\n",
                "    try:\n",
                "        while True:\n",
                "            if backend_process.poll() is not None:\n",
                "                print(\"Backend server shut down unexpectedly.\")\n",
                "                break\n",
                "            if tunnel_process.poll() is not None:\n",
                "                print(\"Cloudflare tunnel shut down unexpectedly.\")\n",
                "                break\n",
                "            time.sleep(2.0)\n",
                "    except KeyboardInterrupt:\n",
                "        print(\"\\nInterrupt signal received. Terminating processes...\")\n",
                "    finally:\n",
                "        backend_process.terminate()\n",
                "        tunnel_process.terminate()\n",
                "        backend_process.wait()\n",
                "        tunnel_process.wait()\n",
                "        print(\"Processes cleaned up cleanly.\")"
            ]
        }
    ]

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 0
    }

    output_path = "./Adobe_Stock_AI_Upscaler.ipynb"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=1)

    print(f"[OK] Notebook compiled successfully: {output_path}")

if __name__ == "__main__":
    compile_notebook()
